spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#nginx服务器上的静态资源目录
Image:
  menu: "http://47.100.90.111/menu_img/"

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:logback-spring.xml
