spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/menus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: funnyChen
    password: funnyChen123!
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000

user:
  imagePath: "/home/menu_img/user/"
  noteImagePath: "/home/menu_img/user/note_img/"